"""empty message

Revision ID: 0b89d3c09775
Revises: ff20e8f20f34
Create Date: 2021-10-28 13:52:04.932231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b89d3c09775'
down_revision = 'ff20e8f20f34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categories', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('categories_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'article', 'categories', ['categories_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'categories_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
