"""empty message

Revision ID: 2de54294d904
Revises: 8031a6aeef27
Create Date: 2021-10-24 11:22:23.040081

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2de54294d904'
down_revision = '8031a6aeef27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=11), nullable=True))
    op.drop_index('phone', table_name='user')
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone', mysql.VARCHAR(length=11), nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('phone', 'user', ['phone'], unique=True)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
