"""empty message

Revision ID: 77ded3948983
Revises: 0b89d3c09775
Create Date: 2021-11-09 14:05:16.472078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77ded3948983'
down_revision = '0b89d3c09775'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('img', sa.String(length=500), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'img')
    # ### end Alembic commands ###
